############################
### Description on files ###
############################


=======================================================================================================================================================
=======================================================================================================================================================
|	FILES					|	DESCRIPTION
=======================================================================================================================================================
=======================================================================================================================================================
|	ICA.py					|	Module for related work on ICA.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	OnlineAnomalyPrediction.py		|	Online processing Method. Feature set is created using days before the news paper article is reported.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	OnlineAnomalyPrediction_VARIATION.py	|	A simple variation. Feature set is created using days before and after the news paper article is reported.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	Kfold_OnlineAnomaly_Prediciton.py	|	A 4-fold Cross-Validation implementation of Online Anomaly Prediction.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	RuleBasedAnomalyDetection.py		|	A Hypothesis based model. Refer this file for more details.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	Processing_arrival.py			|	This file handles Mandi arrival data. It generate arrivals for state and entire nation.
-------------------------------------------------------------------------------------------------------------------------------------------------------
|	seasonal_model.py			|	This approach models seasonal behavior of Time Series. Refer this file for more details.
-------------------------------------------------------------------------------------------------------------------------------------------------------

Seasonal model: Clustering of years, creating seasonal time series.

Preprocess arrivals data. Along with that, MaharastraArrival.csv, NationalArrival.csv contains data generated by this file. 
